### ISSUE TITLE
Central id.mapic.io server

### ISSUE THREAD

**Issue by knutole** [mapic/engine#2]
#### Main purpose
1. Authenticate users. 
2. Hub for chat, real-time collaboration.
3. Analytics.
4. Account page for users.
#### Features
- Give `access_token` in return for `username` + `password`. Not for user-level permissions like `create_project`.
- Must work with several `id` servers, including local hosts behind firewall.
- Run on servers to ensure redundancy. 
- Stores user contact details, including:
- Handle all invites, etc.
- Needs to communicate quite closely with `engine`
- Should be passive, ie. only responding to requests, no outgoing connections to eg. `engine`.

``` js
{
    user_id : "",
    username : "",
    firstName : "",
    lastName : "",
    contacts : [
        "user_id",
        "user_id"
    ],
    created : "",
    company : "",
    job_title : "",
    age : "",
    education : "",
    avatar : "",
    social : {
        twitter : "",
        facebook : "",
        linkedin : "",
        google : "",
        github : "",
    },
    host : {
        domain : "", // which server user belongs to (where data lives)
    },
}
```
- Move most of the keys on `model/user.js` to `id.mapic.io` (all except `id, pg, super`).

**Comment by knutole** [comment]
## Todo
- [ ] Set up standalone Docker container with Redis + Node webserver. 
- [ ] Simple API: 
    - [ ] Verify `access_token` and return user.
    - [ ] Create user
    - [ ] Delete user
    - [ ] Update user
    - [ ] Update user password
    - [ ] Add/remove contacts
    - [ ] Add social media account, import data from social media account
    - [ ] Relay chat messages
    - [ ] Receive analytics
    - [ ] Send user invite
    - [ ] Send user email
    - [ ] Send user message by Slack, Twitter, etc.
    - [ ] Import/export users to other id servers.
- [ ] Create ccount page where user can access GUI of profile @ id.mapic.io. 
- [ ] Redundancy: create network of Docker containers on AWS, with synced Redis stores. 
- [ ] Tests: Create complete and thorough tests for any and all contingency.

### Refactor
- [ ] Move `access_token` check away from `engine`.
- [ ] Make all `access_token` request direct to `id.mapic.io` (like `mile`)
